### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by HoyaAm** [umd-huang-lab/VLM-Poisoning#1]
Thank you very much for your excellent research, but there was a bit of a problem when I tried to reproduce it.

The following error occurs when I run `bash benchmark/benchmark_llava_gqa.sh`. 

How can I get the corresponding file? Can you directly provide the download of the corresponding file？

![图片](https://github.com/user-attachments/assets/2292ac2e-7f22-4866-ad84-20db86e13275)

**Comment by Yuancheng-Xu** [comment]
Hi! It seems that you are running the benchmark code to evaluate the performance on the gqa dataset. This dataset is very large, so I did not upload it on GitHub.

You can follow the official evaluation guide in llava [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md), which provides link to download the gqa dataset, along with others (such as VQA, etc).
